### spring配置
spring:
  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp18oc8h1ey3l7638fo.mysql.rds.aliyuncs.com:33906/timo?useSSL=false&characterEncoding=utf-8
    username: zhongliang
    password: yuanian@123!!!